set_property SRC_FILE_INFO {cfile:C:/Users/40227910/Desktop/MC_CRO_PUF/MC_CRO_PUF.srcs/constrs_1/imports/new/Rounting.xdc rfile:../../../MC_CRO_PUF.srcs/constrs_1/imports/new/Rounting.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/40227910/Desktop/MC_CRO_PUF/MC_CRO_PUF.srcs/constrs_1/new/Routing_1.xdc rfile:../../../MC_CRO_PUF.srcs/constrs_1/new/Routing_1.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A3 I1:A4} [get_cells design_1_i/Test_CRO_0/inst/Enable_A]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A1]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A2]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A3]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A4]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A5]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A6]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A7]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A8]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A9]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A10]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A11]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A12]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A13]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A14]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A15]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A16]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A17]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A18]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A19]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A20]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A21]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A22]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A23]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A24]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A25]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A26]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A27]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A28]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A29]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A30]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A31]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A32]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A33]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A34]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A35]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A36]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A37]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A38]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A39]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A40]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A41]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A42]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A43]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A44]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A45]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A46]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A47]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A48]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A49]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A50]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A51]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A52]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A53]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A54]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A55]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A56]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A57]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A58]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A59]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A60]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A61]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A62]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A63]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6} [get_cells design_1_i/Test_CRO_0/inst/MUX_A64]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A4 I1:A3} [get_cells design_1_i/Test_CRO_0/inst/Enable_B]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B1]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B2]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B3]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B4]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B5]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B6]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B7]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B8]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B9]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B10]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B11]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B12]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B13]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B14]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B15]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B16]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B17]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B18]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B19]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B20]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B21]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B22]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B23]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B24]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B25]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B26]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B27]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B28]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B29]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B30]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B31]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B32]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B33]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B34]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B35]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B36]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B37]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B38]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B39]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B40]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B41]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B42]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B43]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B44]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B45]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B46]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B47]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B48]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B49]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B50]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B51]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B52]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B53]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B54]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B55]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B56]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B57]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B58]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B59]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B60]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B61]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B62]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B63]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3} [get_cells design_1_i/Test_CRO_0/inst/MUX_B64]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 NN6BEG0 LV0 LV0 LV0 NN6BEG1 NN6BEG1 NL1BEG0  { IMUX0 CLBLM_L_A3 }  IMUX16 CLBLM_L_B3 }  } [get_nets {design_1_i/Test_CRO_0/inst/A64[0]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 NL1BEG0 NR1BEG0 LV0 LV0 LV0 NN6BEG3 NL1BEG2 NL1BEG1  { IMUX10 CLBLM_L_A4 }  IMUX26 CLBLM_L_B4 }  } [get_nets {design_1_i/Test_CRO_0/inst/A64[1]}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A3 I1:A4} [get_cells design_1_i/Test_CRO_1/inst/Enable_A]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A1]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A2]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A3]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A4]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A5]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A6]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A7]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A8]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A9]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A10]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A11]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A12]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A13]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A14]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A15]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A16]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A17]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A18]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A19]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A20]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A21]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A22]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A23]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A24]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A25]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A26]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A27]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A28]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A29]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A30]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A31]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A32]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A33]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A34]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A35]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A36]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A37]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A38]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A39]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A40]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A41]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A42]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A43]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A44]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A45]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A46]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A47]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A48]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A49]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A50]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A51]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A52]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A53]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A54]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A55]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A56]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A57]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A58]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A59]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A60]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A61]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A62]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A63]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A2 I1:A1 I3:A6 } [get_cells design_1_i/Test_CRO_1/inst/MUX_A64]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A4 I1:A3} [get_cells design_1_i/Test_CRO_1/inst/Enable_B]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B1]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B2]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B3]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B4]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B5]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B6]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B7]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B8]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B9]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B10]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B11]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B12]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B13]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B14]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B15]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B16]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B17]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B18]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B19]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B20]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B21]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B22]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B23]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B24]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B25]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B26]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B27]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B28]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B29]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B30]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B31]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B32]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B33]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B34]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B35]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B36]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B37]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B38]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B39]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B40]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B41]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B42]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B43]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B44]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B45]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B46]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B47]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B48]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B49]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B50]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B51]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B52]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B53]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B54]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B55]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B56]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B57]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B58]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B59]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B60]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B61]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B62]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B63]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I3:A3 } [get_cells design_1_i/Test_CRO_1/inst/MUX_B64]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 NN6BEG0 LV0 LV0 LV0 NN6BEG1 NN6BEG1 NL1BEG0  { IMUX0 CLBLM_L_A3 }  IMUX16 CLBLM_L_B3 }  } [get_nets {design_1_i/Test_CRO_1/inst/A64[0]}]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 NL1BEG0 NR1BEG0 LV0 LV0 LV0 NN6BEG3 NL1BEG2 NL1BEG1  { IMUX10 CLBLM_L_A4 }  IMUX26 CLBLM_L_B4 }  } [get_nets {design_1_i/Test_CRO_1/inst/A64[1]}]
